# Generated by Django 2.1.7 on 2019-07-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmissions',
            name='content_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
