# Generated by Django 2.1.7 on 2019-08-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_auto_20190718_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='missiondata',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
