# Generated by Django 2.1.7 on 2019-08-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_missiondata_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missiondata',
            name='profile_fn',
        ),
    ]
