# Generated by Django 2.1.7 on 2019-08-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_remove_missiondata_profile_fn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missiondata',
            name='name',
        ),
    ]
