# Generated by Django 2.1.7 on 2019-08-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_remove_missiondata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmissions',
            name='content',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
