# Generated by Django 2.1.7 on 2019-08-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_auto_20190823_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmissions',
            name='content',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
