# Generated by Django 2.1.7 on 2019-08-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0008_auto_20190823_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmissions',
            name='content',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
