# Generated by Django 2.2.6 on 2019-12-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0009_auto_20190823_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transmissions',
            name='time_offset',
        ),
        migrations.RemoveField(
            model_name='transmissions',
            name='time_slot',
        ),
        migrations.AddIndex(
            model_name='transmissions',
            index=models.Index(fields=['mission'], name='mission_idx'),
        ),
    ]
