# Generated by Django 2.2.6 on 2019-12-30 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0011_auto_20191230_1840'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transmissions',
            name='mission_idx',
        ),
    ]
