# Generated by Django 2.1.7 on 2019-03-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Components',
            new_name='Component',
        ),
        migrations.RenameModel(
            old_name='Sectors',
            new_name='Sector',
        ),
    ]
