# Generated by Django 2.1.7 on 2019-03-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20190303_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='cbp_component',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='configuration',
            new_name='file_1',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='cbp_sector',
            new_name='sector',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='photo_6',
        ),
        migrations.AddField(
            model_name='asset',
            name='file_2',
            field=models.FileField(blank=True, upload_to='files/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='asset',
            name='file_3',
            field=models.FileField(blank=True, upload_to='files/%y/%m/%d'),
        ),
    ]
