# Generated by Django 2.1.7 on 2019-03-05 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20190305_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='file_1',
            new_name='file_main',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='photo_1',
        ),
    ]
