# Generated by Django 2.1.7 on 2019-03-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20190311_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='in_service',
            field=models.BooleanField(default=False),
        ),
    ]
