# Generated by Django 2.1.7 on 2019-03-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_asset_in_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='in_service',
            new_name='is_available',
        ),
    ]
